print('Введите расположение фигуры!')
hor = float(input('По горизонтали: '))
ver = float(input('По вертикали: '))
print()
print('Фигура находится в клетке ' + '(' + str(int(hor*10)) + ',' + str(int(ver*10)) + ')')